[package]
name = "smoosh_ds"
version = "0.1.0"
authors = ["Alma Thaler <at564@cornell.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
